USE [master]
GO

/****** Object:  Database [LibraryDatabase]    Script Date: 06/05/2022 13:17:25 ******/
CREATE DATABASE [LibraryDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LibraryDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LibraryDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LibraryDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LibraryDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LibraryDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LibraryDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LibraryDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LibraryDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LibraryDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LibraryDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [LibraryDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LibraryDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LibraryDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LibraryDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LibraryDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LibraryDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LibraryDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LibraryDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LibraryDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LibraryDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LibraryDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LibraryDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LibraryDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LibraryDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LibraryDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LibraryDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LibraryDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LibraryDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LibraryDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [LibraryDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LibraryDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LibraryDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LibraryDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LibraryDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LibraryDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LibraryDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LibraryDatabase] SET  READ_WRITE 
GO

